# 开发环境配置
server:
  port: 8077

# AWS S3配置（开发环境）
# 存储服务配置
storage:
  default: ceph-s3
  providers:
    - type: ceph-s3
      enabled: true
    - type: hdfs
      enabled: false
    - type: minio
      enabled: false

# AWS S3配置（用于Ceph连接）
aws:
  s3:
    accessKeyId: ZUNV3E08FVAQPSWC1Q41
    secretAccessKey: dacVadaDCVTZ3RmGnv2PSFVKSyOgM9lSAaSUGxuw
    region: us-east-1
    endpoint: http://10.170.6.40:31033
    bucket: default

# 日志配置
logging:
  file:
    path: D:\logs
  level:
    com.im.storage: DEBUG
